#!/usr/bin/env bash
# Displays information about subdomains.
# shellcheck disable=SC2086

dns_lookup () {
	echo -n "The subdomain ""$subdomain"
	dig "$1" +noall +answer | awk 'NF==5 {print " is a", $(NF-1), "record and points to", $NF}'
}

if [ -n "$2" ]; then
	subdomains=$2
else
	subdomains=("www" "lb-01" "web-01" "web-02")
fi

if [ -n "$1" ]; then
	domain=$1
	for subdomain in "${subdomains[@]}";do
		dns_lookup "$subdomain.$domain"
	done
fi
