#!/usr/bin/env bash
# Configures NGINX on a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo apt-get -y install curl

echo "Hello World!" > /var/www/html/index.html

# setup redirection
sudo sed -i "/server_name _/ a\\\trewrite ^/redirect_me/?.*$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo service nginx restart
