#!/usr/bin/env bash
# Configures NGINX on a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install curl

# Assign ownership to the account that we are currently signed in to
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html

# setup redirection
sudo sed -i "/server_name/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
