#!/usr/bin/env bash
# Installation and configuration of HAproxy on Ubuntu 20.04
# This script should be run with administrative privileges, 'sudo or root'.

apt update -y && apt upgrade -y

# Add the Personal Package Archive (PPA) into the list of apt sources
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt update -y

# Install HAproxy
apt install -y haproxy
service haproxy restart

# Configure HAproxy to distribute workload between web-01 and web-02
haproxy_config="/etc/haproxy/haproxy.cfg"
echo -e "" >> "$haproxy_config"
echo -e "frontend http" >> "$haproxy_config"
echo -e "\tbind *:80" >> "$haproxy_config"
echo -e "\tmode http" >> "$haproxy_config"
echo -e "\tdefault_backend web-backend" >> "$haproxy_config"
echo -e "" >> "$haproxy_config"
echo -e "backend web-backend" >> "$haproxy_config"
echo -e "\tbalance roundrobin" >> "$haproxy_config"
echo -e "\tserver web-01 100.26.213.68:80 check" >> "$haproxy_config"
echo -e "\tserver web-02 35.153.50.104:80 check" >> "$haproxy_config"

service haproxy restart
