#!/usr/bin/env bash
# Installs ufw firewall, block all incoming traffic, allow specific ports.
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
yes "Y" | sudo ufw enable
