#!/usr/bin/env bash
# changes the ip addresses of 'localhost' and 'facebook.com'

cp /etc/hosts ~/hosts.new

# delete all lines containing the string 'localhost'
sed -i '/localhost/d' ~/hosts.new

# delete all lines containing the string 'facebook.com'
sed -i '/facebook.com/d' ~/hosts.new

# write the new IP mappings
echo "127.0.0.2	localhost" >> ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
