#!/usr/bin/env bash
# run the whoami command under the user passed as an argument
username="syslog"

# Create syslog user with a home directory
sudo useradd -m -s /bin/bash "$username"

sudo -u "$1" whoami
