#!/usr/bin/env bash
# Configure nginx to run as the nginx user
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
